### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MKKing6** [Basicprogrammer10/NoseBot#6]
you suck. ha imiagine

**Comment by connorslade** [comment]
fuck you
<br>
<br>
<br>
*imagine*

**Comment by MKKing6** [comment]
> fuck you _imagine_

you suck still

**Comment by connorslade** [comment]
you think i dont know?

**Comment by MKKing6** [comment]
i mean you are dumb enough to not know that yourself

**Comment by connorslade** [comment]
so your saying... i dont know i suck at knowing that i suck

**Comment by MKKing6** [comment]
yes

**Comment by connorslade** [comment]
:|

**Comment by MKKing6** [comment]
what else would it be

**Comment by connorslade** [comment]
🍲 <= Bisque

**Comment by MKKing6** [comment]
![image](https://user-images.githubusercontent.com/69699405/138799167-895584fa-a638-48c3-b046-0c0aec16912b.png)

**Comment by connorslade** [comment]
![43270b32b129ffb6](https://user-images.githubusercontent.com/50306817/138799230-f824357f-230d-4bcc-8a93-bfa4f7f77e0d.png)

**Comment by MKKing6** [comment]
imagine liking bisques, coudln't be me 
![image](https://user-images.githubusercontent.com/69699405/138799206-9f80a1ff-480b-4b34-b5df-7969505742fa.png)
![image](https://user-images.githubusercontent.com/69699405/138799240-40cf968e-b5ea-4a9b-8c5a-89c920cd5946.png)
![image](https://user-images.githubusercontent.com/69699405/138799267-c2d9ff95-9679-4e5f-b55c-a53b0069cbe1.png)
![image](https://user-images.githubusercontent.com/69699405/138799289-6d76baf2-9953-4f29-9db3-7fbadcb61f6a.png)
![image](https://user-images.githubusercontent.com/69699405/138799296-441164ad-7c16-432d-8300-f4dece3a364b.png)

**Comment by connorslade** [comment]
![image](https://user-images.githubusercontent.com/50306817/138799471-8007e74d-b27d-46e8-ab12-cfc86e528175.png)

**Comment by MKKing6** [comment]
![image](https://user-images.githubusercontent.com/69699405/138804845-cd020c78-c6ae-4f3e-9b6a-a70eeb3e0c24.png)
